services:
  db:
    image: postgres:16
    container_name: gym_management_db
    environment:
      POSTGRES_USER: gym_management
      POSTGRES_PASSWORD: gym_management
      POSTGRES_DB: gym_management
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
